id: P2855E393
initial_creation_type: input
source_metadata:
  title: Parting from the Four Attachments
  language: es
  description: 'A series of texts related to the famous four-line instruction that
    Sachen Kunga Nyingpo (1092–1158) received from Mañjuśrī:'
  volume:
    c914e4352cf54109b2a726d36e757619:
      title: Supplement to the Omniscient Ngorchen Kunga Zangpo’s Prayer to the Lineage
        of Parting from the Four Attachments
      parent: Lineage Prayers
    d7b97f2f7c3f4d418a6f348e6529a0f6:
      title: Prayer to the Lineage of Parting from the Four Attachments
      parent: Lineage Prayers
    e8e86642062a4e889f952f4fca02e718:
      title: The Instructions on Parting from the Four Attachments
      parent: Root Text
    cbc4c75d26ab4456a171a6ae6a348999:
      title: Parting from the Four Attachments
      parent: Commentaries
    4aff10b734e64afb8982db44cc6b60d9:
      title: Nubpa Rigdzin Drak's Parting from the Four Attachments
      parent: Commentaries
    7941a109aae4457589c9fec59e058eba:
      title: Sakya Paṇḍita’s Instruction on Parting from the Four Attachments
      parent: Commentaries
    72bce32156bf47c4a0449daaadc646a4:
      title: 'Nectar of the Heart: An Experiential Song of Parting from the Four Attachments'
      parent: Song
created_at: '2022-03-01T05:02:13.481504'
last_modified_at: '2022-03-01T05:02:13.481507'
